#include "lang.h"
#include "../fs/vfs.h"

// ============================================================
//  lang.c — Tabelas de strings PT/EN e lógica de tr()
// ============================================================

static Lang g_lang = LANG_PT;

static VfsNode* lang_preferences_file(void) {
    VfsNode* file = vfs_resolve(vfs_root(), "/etc/haos.lang");
    if (file) return file;

    VfsNode* etc = vfs_resolve(vfs_root(), "/etc");
    return etc ? vfs_touch(etc, "haos.lang") : NULL;
}

// ---- Tabela: Português ----------------------------------------
static const char* const g_pt[STR_COUNT] = {
    [STR_YES]                   = "Sim",
    [STR_NO]                    = "Nao",
    [STR_OK]                    = "OK",
    [STR_CANCEL]                = "Cancelar",
    [STR_CLOSE]                 = "Fechar",

    [STR_BOOT_SUBTITLE]         = "Home-built Operating System  v1.1",
    [STR_BOOT_MSG_00] = "Inicializando hardware...",
    [STR_BOOT_MSG_01] = "Configurando GDT...",
    [STR_BOOT_MSG_02] = "Carregando IDT...",
    [STR_BOOT_MSG_03] = "Inicializando PIC...",
    [STR_BOOT_MSG_04] = "Configurando timer 100Hz...",
    [STR_BOOT_MSG_05] = "Detectando memoria...",
    [STR_BOOT_MSG_06] = "Alocando shadow buffer...",
    [STR_BOOT_MSG_07] = "Carregando drivers...",
    [STR_BOOT_MSG_08] = "Inicializando teclado PS/2...",
    [STR_BOOT_MSG_09] = "Inicializando mouse PS/2...",
    [STR_BOOT_MSG_10] = "Inicializando GUI...",
    [STR_BOOT_MSG_11] = "Carregando gerenciador de janelas...",
    [STR_BOOT_MSG_12] = "Preparando area de trabalho...",
    [STR_BOOT_MSG_13] = "Renderizando fundo...",
    [STR_BOOT_MSG_14] = "Aplicando paleta de cores...",
    [STR_BOOT_MSG_15] = "Compilando icones...",
    [STR_BOOT_MSG_16] = "Iniciando servicos...",
    [STR_BOOT_MSG_17] = "Carregando terminal...",
    [STR_BOOT_MSG_18] = "Finalizando inicializacao...",
    [STR_BOOT_MSG_19] = "Bem-vindo ao HAOS!",

    [STR_LOGIN_TITLE]            = "HAOS",
    [STR_LOGIN_WELCOME_BACK]     = "Bem-vindo (a) de volta,",
    [STR_LOGIN_FIRST_BOOT_TITLE] = "Vamos configurar seu usuario",
    [STR_LOGIN_NAME_PROMPT]      = "Como podemos te chamar?",
    [STR_LOGIN_NAME_PLACEHOLDER] = "Seu nome",
    [STR_LOGIN_ENTER_BTN]        = "Entrar",
    [STR_LOGIN_DEFAULT_USER]     = "Usuario",
    [STR_LOGIN_NEXT_BTN]              = "Avancar",
    [STR_LOGIN_PASSWORD_TITLE]        = "Proteja sua conta",
    [STR_LOGIN_PASSWORD_PROMPT]       = "Crie uma senha (opcional)",
    [STR_LOGIN_PASSWORD_PLACEHOLDER]  = "Senha",
    [STR_LOGIN_SKIP_PASSWORD_BTN]     = "Nao quero senha",
    [STR_LOGIN_PASSWORD_PROMPT_ENTER] = "Digite sua senha",
    [STR_LOGIN_PASSWORD_PLACEHOLDER_ENTER] = "Senha",

    [STR_CONFIG_ACCOUNT_SECTION] = "Conta",

    [STR_START_BUTTON]          = "# Iniciar",
    [STR_TERMINAL]              = "Terminal",
    [STR_ABOUT]                 = "Sobre",
    [STR_SETTINGS]              = "Configuracoes",
    [STR_RESTART]               = "Reiniciar",
    [STR_SHUTDOWN]              = "Desligar",
    [STR_MENU_CLOSE_HINT]       = "[ESC] fechar",
    [STR_DESKTOP_HINT_BAR]      = "[S] Menu  [T] Terminal  [A] Sobre  [E] Editor  [C] Config",
    [STR_STARTMENU_HEADER]      = "HAOS  v1.1",

    [STR_ICON_TERMINAL]         = "Terminal",
    [STR_ICON_ABOUT]            = "Sobre",
    [STR_ICON_SETTINGS]         = "Config.",

    [STR_ABOUT_WINDOW_TITLE]    = "Sobre o HAOS",
    [STR_ABOUT_HEADER]          = "HAOS -- Home-built OS",
    [STR_ABOUT_VERSION]         = "Versao    : 1.1",
    [STR_ABOUT_ARCH]            = "Arq.      : x86-64 Long Mode",
    [STR_ABOUT_BOOT]            = "Boot      : GRUB2 + Multiboot2",
    [STR_ABOUT_VIDEO]           = "Video     : VESA VBE 1024x768 32bpp",
    [STR_ABOUT_GUI]             = "GUI       : double-buffered FB",
    [STR_ABOUT_INPUT]           = "Input     : PS/2 Keyboard + Mouse",
    [STR_ABOUT_KERNEL]          = "Kernel    : C freestanding",
    [STR_ABOUT_FOOTER]          = "Desenvolvido do zero em C/C++ + ASM",

    [STR_CONFIG_WINDOW_TITLE]   = "Configuracoes",
    [STR_CONFIG_WALLPAPER]      = "Papel de parede:",
    [STR_CONFIG_DEFAULT_WALLPAPER] = "Padrao (gradiente)",
    [STR_CONFIG_MODE]           = "Modo:",
    [STR_CONFIG_MODE_FILL]      = "Preencher",
    [STR_CONFIG_MODE_CENTER]    = "Centralizar",
    [STR_CONFIG_MODE_TILE]      = "Lado a lado",
    [STR_CONFIG_DEVICE]         = "Dispositivo:",
    [STR_CONFIG_CPU]            = "CPU:",
    [STR_CONFIG_CORES]          = "Nucleos:",
    [STR_CONFIG_RAM_TOTAL]      = "RAM Total:",
    [STR_CONFIG_RAM_FREE]       = "RAM Livre:",
    [STR_CONFIG_HEAP]           = "Heap Kernel:",
    [STR_CONFIG_LANGUAGE]       = "Idioma:",
    [STR_CONFIG_LANG_PT]        = "Portugues",
    [STR_CONFIG_LANG_EN]        = "English",
    [STR_CONFIG_FOOTER_HINT]    = "j/k: navegar  1/2/3: modo  L: idioma  ESC: fechar",
    [STR_CONFIG_CATEGORY_SYSTEM]          = "Sistema",
    [STR_CONFIG_CATEGORY_PERSONALIZATION] = "Personalizacao",
    [STR_CONFIG_CATEGORY_ABOUT]           = "Sobre o Sistema",
    [STR_CONFIG_SECTION_LANGUAGE_DESC]    = "Idioma do sistema e da interface.",

    [STR_TERM_WELCOME_1]        = "  HAOS Shell v1.2  --  Digite 'help' para ajuda",
    [STR_TERM_WELCOME_2]        = "  Use o mouse para arrastar esta janela.",
    [STR_TERM_HELP_HEADER]      = "Comandos do HAOS Shell:",
    [STR_TERM_HELP_HELP]        = "  help          -- esta ajuda",
    [STR_TERM_HELP_CLEAR]       = "  clear         -- limpa a tela",
    [STR_TERM_HELP_ECHO]        = "  echo <texto>  -- imprime texto",
    [STR_TERM_HELP_ABOUT]       = "  about         -- sobre o HAOS",
    [STR_TERM_HELP_DATE]        = "  date          -- data/hora atual",
    [STR_TERM_HELP_MEM]         = "  mem           -- informacoes de memoria",
    [STR_TERM_HELP_REBOOT]      = "  reboot        -- reinicia o sistema",
    [STR_TERM_HELP_LANG]        = "  lang <pt|en>  -- muda o idioma do sistema",
    [STR_TERM_HELP_FS_HEADER]   = "Sistema de Arquivos:",
    [STR_TERM_HELP_PWD]         = "  pwd           -- diretorio atual",
    [STR_TERM_HELP_LS]          = "  ls [dir]      -- lista arquivos",
    [STR_TERM_HELP_CD]          = "  cd <dir>      -- muda diretorio",
    [STR_TERM_HELP_MKDIR]       = "  mkdir <nome>  -- cria diretorio",
    [STR_TERM_HELP_TOUCH]       = "  touch <nome>  -- cria arquivo vazio",
    [STR_TERM_HELP_CAT]         = "  cat <arq>     -- exibe conteudo",
    [STR_TERM_HELP_WRITE]       = "  write <arq> <texto> -- escreve em arquivo",
    [STR_TERM_HELP_APPEND]      = "  append <arq> <texto> -- acrescenta ao arquivo",
    [STR_TERM_HELP_RM]          = "  rm <nome>     -- remove arquivo/diretorio",
    [STR_TERM_HELP_STAT]        = "  stat <nome>   -- informacoes do arquivo",

    [STR_TERM_ABOUT_TITLE]      = "  HAOS v1.2 -- Home-built OS",
    [STR_TERM_ABOUT_ARCH]       = "  Arquitetura : x86-64 (Long Mode)",
    [STR_TERM_ABOUT_BOOT]       = "  Boot        : GRUB2 + Multiboot2",
    [STR_TERM_ABOUT_VIDEO]      = "  Video       : VESA VBE 1024x768 32bpp",
    [STR_TERM_ABOUT_GUI]        = "  GUI         : double-buffered framebuffer",
    [STR_TERM_ABOUT_INPUT]      = "  Input       : PS/2 Keyboard + Mouse",
    [STR_TERM_ABOUT_FS]         = "  FS          : HAOS-VFS (heap tree)",

    [STR_TERM_MEM_HEAP]         = "  Heap: 12 MB (bump allocator)",
    [STR_TERM_MEM_SHADOW]       = "  Shadow buffer: ~3 MB (double buffering)",
    [STR_TERM_MEM_BGCACHE]      = "  BG cache: ~3 MB",
    [STR_TERM_MEM_VFS]          = "  VFS: alocado na heap",

    [STR_TERM_LS_DIR_NOT_FOUND] = "ls: diretorio nao encontrado",
    [STR_TERM_LS_NOT_A_DIR]     = "ls: nao e um diretorio",
    [STR_TERM_LS_EMPTY]         = "  (diretorio vazio)",
    [STR_TERM_CD_NOT_FOUND]     = "cd: diretorio nao encontrado",
    [STR_TERM_CD_NOT_A_DIR]     = "cd: nao e um diretorio",
    [STR_TERM_MKDIR_NEED_NAME]  = "mkdir: nome necessario",
    [STR_TERM_MKDIR_FAILED]     = "mkdir: falha (ja existe ou limite atingido)",
    [STR_TERM_TOUCH_NEED_NAME]  = "touch: nome necessario",
    [STR_TERM_TOUCH_FAILED]     = "touch: falha ao criar arquivo",
    [STR_TERM_CAT_NEED_NAME]    = "cat: nome necessario",
    [STR_TERM_CAT_NOT_FOUND]    = "cat: arquivo nao encontrado",
    [STR_TERM_CAT_IS_DIR]       = "cat: e um diretorio",
    [STR_TERM_CAT_EMPTY]        = "(arquivo vazio)",
    [STR_TERM_WRITE_USAGE]      = "write: uso: write <arq> <texto>",
    [STR_TERM_WRITE_EMPTY_NAME] = "write: nome vazio",
    [STR_TERM_WRITE_NOT_A_FILE] = "write: nao e um arquivo",
    [STR_TERM_WRITE_DONE]       = "  escrito.",
    [STR_TERM_APPEND_USAGE]     = "append: uso: append <arq> <texto>",
    [STR_TERM_APPEND_NOT_A_FILE]= "append: nao e um arquivo",
    [STR_TERM_APPEND_DONE]      = "  acrescentado.",
    [STR_TERM_RM_NEED_NAME]     = "rm: nome necessario",
    [STR_TERM_RM_NOT_FOUND]     = "rm: nao encontrado",
    [STR_TERM_RM_CANT_ROOT]     = "rm: nao posso remover o root",
    [STR_TERM_RM_CANT_CWD]      = "rm: nao posso remover o diretorio atual",
    [STR_TERM_RM_DONE]          = "  removido.",
    [STR_TERM_STAT_NEED_NAME]   = "stat: nome necessario",
    [STR_TERM_STAT_NOT_FOUND]   = "stat: nao encontrado",
    [STR_TERM_STAT_NAME]        = "  Nome : ",
    [STR_TERM_STAT_TYPE]        = "  Tipo : ",
    [STR_TERM_STAT_TYPE_DIR]    = "diretorio",
    [STR_TERM_STAT_TYPE_FILE]   = "arquivo",
    [STR_TERM_STAT_SIZE]        = "  Tam  : ",
    [STR_TERM_STAT_ITEMS]       = "  Itens: ",
    [STR_TERM_STAT_PATH]        = "  Path : ",
    [STR_TERM_CMD_NOT_FOUND]    = "  Comando nao encontrado: ",
    [STR_TERM_CMD_NOT_FOUND_HINT] = "  Digite 'help' para ver os comandos.",
    [STR_TERM_DATE_LABEL]       = "  Data: ",
    [STR_TERM_TIME_LABEL]       = "  Hora: ",
    [STR_TERM_LANG_SET_PT]      = "  Idioma alterado para Portugues.",
    [STR_TERM_LANG_SET_EN]      = "  Idioma alterado para Ingles.",
    [STR_TERM_LANG_USAGE]       = "lang: uso: lang <pt|en>",

    [STR_EDITOR_TITLE]         = "Bloco de Notas",
    [STR_EDITOR_SAVED]         = "Salvo!",
    [STR_EDITOR_SAVE_FAILED]   = "Falha ao salvar",
    [STR_EDITOR_COPIED]        = "Copiado!",
    [STR_EDITOR_CUT]           = "Recortado!",
    [STR_EDITOR_PASTED]        = "Colado!",
    [STR_EDITOR_SAVEAS_PROMPT] = "Salvar como (digite o nome do arquivo):",
    [STR_EDITOR_SAVEAS_HINT]   = "[Enter] Salvar   [ESC] Cancelar",
    [STR_EDITOR_UNTITLED]      = "(sem nome)",
    [STR_EDITOR_LINE_LABEL]    = "Lin ",
    [STR_EDITOR_COL_LABEL]     = "  Col ",
    [STR_EDITOR_CHARS_LABEL]   = "  Caract ",
    [STR_ICON_EDITOR]          = "Bloco de Notas",
    [STR_TERM_HELP_EDIT]       = "  edit <nome>   -- abre o bloco de notas",
};

// ---- Tabela: English -------------------------------------------
static const char* const g_en[STR_COUNT] = {
    [STR_YES]                   = "Yes",
    [STR_NO]                    = "No",
    [STR_OK]                    = "OK",
    [STR_CANCEL]                = "Cancel",
    [STR_CLOSE]                 = "Close",

    [STR_BOOT_SUBTITLE]         = "Home-built Operating System  v1.1",
    [STR_BOOT_MSG_00] = "Initializing hardware...",
    [STR_BOOT_MSG_01] = "Setting up GDT...",
    [STR_BOOT_MSG_02] = "Loading IDT...",
    [STR_BOOT_MSG_03] = "Initializing PIC...",
    [STR_BOOT_MSG_04] = "Configuring 100Hz timer...",
    [STR_BOOT_MSG_05] = "Detecting memory...",
    [STR_BOOT_MSG_06] = "Allocating shadow buffer...",
    [STR_BOOT_MSG_07] = "Loading drivers...",
    [STR_BOOT_MSG_08] = "Initializing PS/2 keyboard...",
    [STR_BOOT_MSG_09] = "Initializing PS/2 mouse...",
    [STR_BOOT_MSG_10] = "Initializing GUI...",
    [STR_BOOT_MSG_11] = "Loading window manager...",
    [STR_BOOT_MSG_12] = "Preparing desktop...",
    [STR_BOOT_MSG_13] = "Rendering background...",
    [STR_BOOT_MSG_14] = "Applying color palette...",
    [STR_BOOT_MSG_15] = "Building icons...",
    [STR_BOOT_MSG_16] = "Starting services...",
    [STR_BOOT_MSG_17] = "Loading terminal...",
    [STR_BOOT_MSG_18] = "Finishing startup...",
    [STR_BOOT_MSG_19] = "Welcome to HAOS!",

    [STR_LOGIN_TITLE]            = "HAOS",
    [STR_LOGIN_WELCOME_BACK]     = "Welcome back,",
    [STR_LOGIN_FIRST_BOOT_TITLE] = "Let's set up your user",
    [STR_LOGIN_NAME_PROMPT]      = "What should we call you?",
    [STR_LOGIN_NAME_PLACEHOLDER] = "Your name",
    [STR_LOGIN_ENTER_BTN]        = "Enter",
    [STR_LOGIN_DEFAULT_USER]     = "User",
    [STR_LOGIN_NEXT_BTN]              = "Next",
    [STR_LOGIN_PASSWORD_TITLE]        = "Protect your account",
    [STR_LOGIN_PASSWORD_PROMPT]       = "Create a password (optional)",
    [STR_LOGIN_PASSWORD_PLACEHOLDER]  = "Password",
    [STR_LOGIN_SKIP_PASSWORD_BTN]     = "I don't want a password",
    [STR_LOGIN_PASSWORD_PROMPT_ENTER] = "Enter your password",
    [STR_LOGIN_PASSWORD_PLACEHOLDER_ENTER] = "Password",

    [STR_CONFIG_ACCOUNT_SECTION] = "Account",

    [STR_START_BUTTON]          = "# Start",
    [STR_TERMINAL]              = "Terminal",
    [STR_ABOUT]                 = "About",
    [STR_SETTINGS]              = "Settings",
    [STR_RESTART]               = "Restart",
    [STR_SHUTDOWN]              = "Shut down",
    [STR_MENU_CLOSE_HINT]       = "[ESC] close",
    [STR_DESKTOP_HINT_BAR]      = "[S] Menu  [T] Terminal  [A] About  [E] Editor  [C] Settings",
    [STR_STARTMENU_HEADER]      = "HAOS  v1.1",

    [STR_ICON_TERMINAL]         = "Terminal",
    [STR_ICON_ABOUT]            = "About",
    [STR_ICON_SETTINGS]         = "Settings",

    [STR_ABOUT_WINDOW_TITLE]    = "About HAOS",
    [STR_ABOUT_HEADER]          = "HAOS -- Home-built OS",
    [STR_ABOUT_VERSION]         = "Version   : 1.1",
    [STR_ABOUT_ARCH]            = "Arch.     : x86-64 Long Mode",
    [STR_ABOUT_BOOT]            = "Boot      : GRUB2 + Multiboot2",
    [STR_ABOUT_VIDEO]           = "Video     : VESA VBE 1024x768 32bpp",
    [STR_ABOUT_GUI]             = "GUI       : double-buffered FB",
    [STR_ABOUT_INPUT]           = "Input     : PS/2 Keyboard + Mouse",
    [STR_ABOUT_KERNEL]          = "Kernel    : C freestanding",
    [STR_ABOUT_FOOTER]          = "Built from scratch in C/C++ + ASM",

    [STR_CONFIG_WINDOW_TITLE]   = "Settings",
    [STR_CONFIG_WALLPAPER]      = "Wallpaper:",
    [STR_CONFIG_DEFAULT_WALLPAPER] = "Default (gradient)",
    [STR_CONFIG_MODE]           = "Mode:",
    [STR_CONFIG_MODE_FILL]      = "Fill",
    [STR_CONFIG_MODE_CENTER]    = "Center",
    [STR_CONFIG_MODE_TILE]      = "Tile",
    [STR_CONFIG_DEVICE]         = "Device:",
    [STR_CONFIG_CPU]            = "CPU:",
    [STR_CONFIG_CORES]          = "Cores:",
    [STR_CONFIG_RAM_TOTAL]      = "Total RAM:",
    [STR_CONFIG_RAM_FREE]       = "Free RAM:",
    [STR_CONFIG_HEAP]           = "Kernel Heap:",
    [STR_CONFIG_LANGUAGE]       = "Language:",
    [STR_CONFIG_LANG_PT]        = "Portuguese",
    [STR_CONFIG_LANG_EN]        = "English",
    [STR_CONFIG_FOOTER_HINT]    = "j/k: navigate  1/2/3: mode  L: language  ESC: close",
    [STR_CONFIG_CATEGORY_SYSTEM]          = "System",
    [STR_CONFIG_CATEGORY_PERSONALIZATION] = "Personalization",
    [STR_CONFIG_CATEGORY_ABOUT]           = "About This System",
    [STR_CONFIG_SECTION_LANGUAGE_DESC]    = "System and interface language.",

    [STR_TERM_WELCOME_1]        = "  HAOS Shell v1.2  --  Type 'help' for assistance",
    [STR_TERM_WELCOME_2]        = "  Use the mouse to drag this window.",
    [STR_TERM_HELP_HEADER]      = "HAOS Shell commands:",
    [STR_TERM_HELP_HELP]        = "  help          -- this help",
    [STR_TERM_HELP_CLEAR]       = "  clear         -- clears the screen",
    [STR_TERM_HELP_ECHO]        = "  echo <text>   -- prints text",
    [STR_TERM_HELP_ABOUT]       = "  about         -- about HAOS",
    [STR_TERM_HELP_DATE]        = "  date          -- current date/time",
    [STR_TERM_HELP_MEM]         = "  mem           -- memory information",
    [STR_TERM_HELP_REBOOT]      = "  reboot        -- restarts the system",
    [STR_TERM_HELP_LANG]        = "  lang <pt|en>  -- change system language",
    [STR_TERM_HELP_FS_HEADER]   = "File System:",
    [STR_TERM_HELP_PWD]         = "  pwd           -- current directory",
    [STR_TERM_HELP_LS]          = "  ls [dir]      -- list files",
    [STR_TERM_HELP_CD]          = "  cd <dir>      -- change directory",
    [STR_TERM_HELP_MKDIR]       = "  mkdir <name>  -- create directory",
    [STR_TERM_HELP_TOUCH]       = "  touch <name>  -- create empty file",
    [STR_TERM_HELP_CAT]         = "  cat <file>    -- show contents",
    [STR_TERM_HELP_WRITE]       = "  write <file> <text>  -- write to file",
    [STR_TERM_HELP_APPEND]      = "  append <file> <text> -- append to file",
    [STR_TERM_HELP_RM]          = "  rm <name>     -- remove file/directory",
    [STR_TERM_HELP_STAT]        = "  stat <name>   -- file information",

    [STR_TERM_ABOUT_TITLE]      = "  HAOS v1.2 -- Home-built OS",
    [STR_TERM_ABOUT_ARCH]       = "  Architecture: x86-64 (Long Mode)",
    [STR_TERM_ABOUT_BOOT]       = "  Boot        : GRUB2 + Multiboot2",
    [STR_TERM_ABOUT_VIDEO]      = "  Video       : VESA VBE 1024x768 32bpp",
    [STR_TERM_ABOUT_GUI]        = "  GUI         : double-buffered framebuffer",
    [STR_TERM_ABOUT_INPUT]      = "  Input       : PS/2 Keyboard + Mouse",
    [STR_TERM_ABOUT_FS]         = "  FS          : HAOS-VFS (heap tree)",

    [STR_TERM_MEM_HEAP]         = "  Heap: 12 MB (bump allocator)",
    [STR_TERM_MEM_SHADOW]       = "  Shadow buffer: ~3 MB (double buffering)",
    [STR_TERM_MEM_BGCACHE]      = "  BG cache: ~3 MB",
    [STR_TERM_MEM_VFS]          = "  VFS: allocated on the heap",

    [STR_TERM_LS_DIR_NOT_FOUND] = "ls: directory not found",
    [STR_TERM_LS_NOT_A_DIR]     = "ls: not a directory",
    [STR_TERM_LS_EMPTY]         = "  (empty directory)",
    [STR_TERM_CD_NOT_FOUND]     = "cd: directory not found",
    [STR_TERM_CD_NOT_A_DIR]     = "cd: not a directory",
    [STR_TERM_MKDIR_NEED_NAME]  = "mkdir: name required",
    [STR_TERM_MKDIR_FAILED]     = "mkdir: failed (already exists or limit reached)",
    [STR_TERM_TOUCH_NEED_NAME]  = "touch: name required",
    [STR_TERM_TOUCH_FAILED]     = "touch: failed to create file",
    [STR_TERM_CAT_NEED_NAME]    = "cat: name required",
    [STR_TERM_CAT_NOT_FOUND]    = "cat: file not found",
    [STR_TERM_CAT_IS_DIR]       = "cat: is a directory",
    [STR_TERM_CAT_EMPTY]        = "(empty file)",
    [STR_TERM_WRITE_USAGE]      = "write: usage: write <file> <text>",
    [STR_TERM_WRITE_EMPTY_NAME] = "write: empty name",
    [STR_TERM_WRITE_NOT_A_FILE] = "write: not a file",
    [STR_TERM_WRITE_DONE]       = "  written.",
    [STR_TERM_APPEND_USAGE]     = "append: usage: append <file> <text>",
    [STR_TERM_APPEND_NOT_A_FILE]= "append: not a file",
    [STR_TERM_APPEND_DONE]      = "  appended.",
    [STR_TERM_RM_NEED_NAME]     = "rm: name required",
    [STR_TERM_RM_NOT_FOUND]     = "rm: not found",
    [STR_TERM_RM_CANT_ROOT]     = "rm: cannot remove root",
    [STR_TERM_RM_CANT_CWD]      = "rm: cannot remove current directory",
    [STR_TERM_RM_DONE]          = "  removed.",
    [STR_TERM_STAT_NEED_NAME]   = "stat: name required",
    [STR_TERM_STAT_NOT_FOUND]   = "stat: not found",
    [STR_TERM_STAT_NAME]        = "  Name : ",
    [STR_TERM_STAT_TYPE]        = "  Type : ",
    [STR_TERM_STAT_TYPE_DIR]    = "directory",
    [STR_TERM_STAT_TYPE_FILE]   = "file",
    [STR_TERM_STAT_SIZE]        = "  Size : ",
    [STR_TERM_STAT_ITEMS]       = "  Items: ",
    [STR_TERM_STAT_PATH]        = "  Path : ",
    [STR_TERM_CMD_NOT_FOUND]    = "  Command not found: ",
    [STR_TERM_CMD_NOT_FOUND_HINT] = "  Type 'help' to see the commands.",
    [STR_TERM_DATE_LABEL]       = "  Date: ",
    [STR_TERM_TIME_LABEL]       = "  Time: ",
    [STR_TERM_LANG_SET_PT]      = "  Language changed to Portuguese.",
    [STR_TERM_LANG_SET_EN]      = "  Language changed to English.",
    [STR_TERM_LANG_USAGE]       = "lang: usage: lang <pt|en>",

    [STR_EDITOR_TITLE]         = "Notepad",
    [STR_EDITOR_SAVED]         = "Saved!",
    [STR_EDITOR_SAVE_FAILED]   = "Failed to save",
    [STR_EDITOR_COPIED]        = "Copied!",
    [STR_EDITOR_CUT]           = "Cut!",
    [STR_EDITOR_PASTED]        = "Pasted!",
    [STR_EDITOR_SAVEAS_PROMPT] = "Save as (type the file name):",
    [STR_EDITOR_SAVEAS_HINT]   = "[Enter] Save   [ESC] Cancel",
    [STR_EDITOR_UNTITLED]      = "(untitled)",
    [STR_EDITOR_LINE_LABEL]    = "Ln ",
    [STR_EDITOR_COL_LABEL]     = "  Col ",
    [STR_EDITOR_CHARS_LABEL]   = "  Chars ",
    [STR_ICON_EDITOR]          = "Notepad",
    [STR_TERM_HELP_EDIT]       = "  edit <name>   -- opens the notepad",
};

void lang_init(void) {
    g_lang = LANG_PT;

    VfsNode* file = vfs_resolve(vfs_root(), "/etc/haos.lang");
    if (file && file->type == VFS_FILE && file->size > 0 && file->data[0] == 'e')
        g_lang = LANG_EN;
}

void lang_set(Lang l) {
    if (l < 0 || l >= LANG_COUNT) return;
    g_lang = l;

    VfsNode* file = lang_preferences_file();
    if (file) vfs_write(file, g_lang == LANG_EN ? "en\n" : "pt\n");
}

Lang lang_get(void) {
    return g_lang;
}

void lang_toggle(void) {
    lang_set((g_lang == LANG_PT) ? LANG_EN : LANG_PT);
}

const char* tr(StrID id) {
    if (id < 0 || id >= STR_COUNT) return "";
    const char* s = (g_lang == LANG_EN) ? g_en[id] : g_pt[id];
    return s ? s : "";
}

const char* lang_name(Lang l) {
    return (l == LANG_EN) ? "English" : "Portugues";
}
